var debug = 0;
var matrix_image_path = 'images/clients/matrix/';
var matrixJSON = {"headings": {
		"left" : [
			{"display_name": "Chemicals"},
			{"display_name": "Consumer Goods & Services"},
			{"display_name": "Energy"},
			{"display_name": "Financial Services"},
			{"display_name": "Industrials"},
			{"display_name": "Life Sciences"},
			{"display_name": "Media & Telecommunications"},
			{"display_name": "Metals & Mining"},
			{"display_name": "Oil & Gas"},
			{"display_name": "Technology"}
    	],
		"bottom" : [
			{"display_name": "Benchmarking & Best Practice Analysis"},
			{"display_name": "Competitive Intelligence"},
			{"display_name": "Customer & Market Insights"},
			{"display_name": "Market Sizing & Analysis"},
			{"display_name": "Mergers & Acquisitions Due Diligence"},
			{"display_name": "Cost Structure Analysis"},
			{"display_name": "New Opportunity Identification & Assessment"},
			{"display_name": "Industry & Technology Trend Analysis"}
    	]		
	},
	"popups": [
		{"image": "matrix_1_1.jpg", "col" : "1", "row" : "1", "industry": "Commercial Terms of Chemical Products in Asia and Europe", "function_name": "", "case_study": "", "blurb": "On behalf of a major producer of chemicals in the Middle East, 10EQS&rsquo; client seeks to evaluate the commercial terms and insights into available process technologies...", "blurb_url": "" + Drupal.settings.basePath + "sites/default/files/case_studies/Industrial Products Chemicals - Commercial Terms of Chemical Products in Asia and Europe.pdf", "case_study_url": "", "id": "11"},
		{"image": "matrix_1_2.jpg", "col" : "1", "row" : "2", "industry": "Best Practices in Eco Tourism for Destinations and Resorts", "function_name": "", "case_study": "<p><strong>Best Practices in Consumer Electronics After-Sales Services</strong></p><p>Provided insight into best practices for Aftersales and Aftermarket Services in Customer Electronics in various geographies, service lines and product lines through collaboration with experts.</p>", "blurb": "10EQS identified top Eco-Tourism destinations and resorts to assess their best practices. The project included benchmarking of the tourism sector in selected high volume destinations in terms of performance, investment laws, and regulatory environment.", "blurb_url": "", "case_study_url": "", "id": "12"},
		{"image": "matrix_1_3.jpg", "col" : "1", "row" : "3", "industry": "Power Sector Restructuring - Insights in Unbundling and Corporatization", "function_name": "", "case_study": "<p><strong>Benchmarking of Independent Power Producers</strong></p><p>Provided benchmarking for Independent Power Producers (IPPs) operating globally, i.e. &quot;pure play&quot; power generating companies (without any distribution or transmission business). Identified the largest globally operating IPPs.</p>", "blurb": "Assessed certain aspects of electricity sector reform in emerging market countries. This included understanding in which countries power sectors have been unbundled and transformed from a holistically organized government-owned entity into a more distributed organizational model (with or without privatization), in which countries this process was viewed as successful and which were not, and where a successful transformation to corporate organizational forms has been done.", "blurb_url": "", "case_study_url": "", "id": "13"},
		{"image": "matrix_1_4.jpg", "col" : "1", "row" : "4", "industry": "Risk Management and Bank Balance Sheet Allocation", "function_name": "", "case_study": "<p><strong>Global Mobile Phone Banking Best Practice Study</strong></p><p>A medium sized European retail bank with a focus on consumer lending assesses expanding its mobile phone banking offer into mobile contactless payments...</p>", "blurb": "A leading international bank wants to analyze the balance sheet allocation of corporate credit risk across different industries and geographies for a set of other leading banks...", "blurb_url": "" + Drupal.settings.basePath + "sites/default/files/case_studies/Risk Management - Risk Management and Bank Balance Sheet Allocation.pdf", "case_study_url": "" + Drupal.settings.basePath + "sites/default/files/case_studies/Mobile Payments - Mobile Payments Trends and Technologies.pdf", "id": "14"},
		{"image": "matrix_1_5.jpg", "col" : "1", "row" : "5", "industry": "Best Practices & Benchmarking of Industrial Customer Financing Solutions", "function_name": "", "case_study": "", "blurb": "Provided a competitive benchmarking analysis of customer financing solutions of major industrial conglomerates. We provided insights into competitors' financing models, how they use them to gain a competitive advantage, and how they approach strategic financing investments.", "blurb_url": "", "case_study_url": "", "id": "14"},
		{"image": "matrix_1_6.jpg", "col" : "1", "row" : "6", "industry": "Best Practices in Tactical Defense of Pharmaceuticals Against Generic Drugs", "function_name": "", "case_study": "", "blurb": "Created a model for the demand of the client's therapeutics and guided the client's internal corporate response to threats and opportunities by coordinating among executives and global knowledge experts to create a tactical playbook across 25 separate worldwide markets.", "blurb_url": "", "case_study_url": "", "id": "14"},
		{"image": "matrix_1_7.jpg", "col" : "1", "row" : "7", "industry": "Best Practices: Mobile Phone Banking Applications", "function_name": "", "case_study": "", "blurb": "Assessed the mobile phone banking industry for a major European retail bank. Analyzed recent trends in mobile phone banking: innovations, user preferences, market regulation and competitive landscape.", "blurb_url": "", "case_study_url": "", "id": "14"},
		{"image": "matrix_1_8.jpg", "col" : "1", "row" : "8", "industry": "High Value Materials Recycling", "function_name": "", "case_study": "", "blurb": "Conducted a broad market analysis of the market for retrieval and reuse of high value raw materials used in technical processes. Delivered bottom-up analysis of 6 high value materials, including Thermal Bond Coat, Phosphor, Yttria, Scintillator/Terbium, Tungsten Carbide and Platinum, to estimate global market size and key participants. Prioritized materials in terms of estimated market opportunity and client fit.", "blurb_url": "", "case_study_url": "", "id": "14"},
		{"image": "matrix_1_9.jpg", "col" : "1", "row" : "9", "industry": "European Fuel Markets", "function_name": "", "case_study": "", "blurb": "Conducted benchmarking and best practice analysis of fuel mixtures and market trends in Europe by producing a landscape study and determined optimal fuel mixture for downstream oil & gas portfolio.", "blurb_url": "", "case_study_url": "", "id": "14"},
		{"image": "matrix_1_10.jpg", "col" : "1", "row" : "10", "industry": "Semiconductor Sales and Marketing Best Practices", "function_name": "", "case_study": "<p><strong>Benchmarking of PC Manufacturers in China</strong></p><p>Provided benchmarking of major PC competitors and industry players in China. Covered 2 modules: organizational design, and capabilities comprising product & solutions, competitive landscape, growth strategy, and go-to-market models.</p>", "blurb": "For a large client, 10EQS benchmarked sales organizations and sales operations across 25+ semiconductor companies (with 500M+ revenue) to understand/develop insights around qualitative and quantitative aspects of sales approaches (using a combination of publicly available data and targeted expert interviews). Findings included rationale for SG&A cost structure/variance, S&M headcount and cost estimation, trends around solution selling, organizational structure/hybrids across geographies, and evolution of key drivers in selling costs.", "blurb_url": "", "case_study_url": "", "id": "14"},
		
		{"image": "matrix_2_1.jpg", "col" : "2", "row" : "1", "industry": "Chemical Company Analysis", "function_name": "", "case_study": "", "blurb": "Analyzed two leading chemical businesses in South Korea. Evaluated each company's leadership, strategy and specific product lines.", "blurb_url": "", "case_study_url": "", "id": "21"},
		{"image": "matrix_2_2.jpg", "col" : "2", "row" : "2", "industry": "Textile Industry in Latin America", "function_name": "", "case_study": "", "blurb": "10EQS provided insights into the textile industry in selected Latin America countries by identifying and characterizing key industry players.", "blurb_url": "", "case_study_url": "", "id": "23"},
		{"image": "matrix_2_3.jpg", "col" : "2", "row" : "3", "industry": "Wind and Solar Competitive Analysis", "function_name": "", "case_study": "", "blurb": "Assessed various aspects of wind and solar power companies in the US and Europe, including: market focus, project development, financing, organization, and financial performance. Also provided a deep dive into four major competitors.", "blurb_url": "", "case_study_url": "", "id": "25"},
		{"image": "matrix_2_4.jpg", "col" : "2", "row" : "4", "industry": "Review of Outsourcing Models of Leading Merchant Acquiring Service Providers", "function_name": "", "case_study": "", "blurb": "Assessed options for outsourcing the merchant acquiring business of a retail bank to organizations specialized in this field. Analyzed which cooperative outsourcing models (especially successful ones) exist for the merchant acquiring business, with focus on cooperation/outsourcing models in emerging markets. Provided facts and figures on outsourcing cases and insights into how the outsourcing partnership with banks has worked.", "blurb_url": "", "case_study_url": "", "id": "25"},
		{"image": "matrix_2_5.jpg", "col" : "2", "row" : "5", "industry": "Software and Services Market for the Aerospace Industry", "function_name": "", "case_study": "", "blurb": "Provided an analysis on the size of different segments of the aviation software, outsourcing and consulting services market (e.g. maintenance, engineering, sourcing, crew scheduling, fleet scheduling, flight scheduling, fuel planning, etc.)", "blurb_url": "", "case_study_url": "", "id": "25"},
		{"image": "matrix_2_6.jpg", "col" : "2", "row" : "6", "industry": "Competitive Analysis of the Software and Services Market for Healthcare Providers", "function_name": "", "case_study": "", "blurb": "10EQS calculated and estimated revenue and profit pool figures per industry segment by drawing from various industry experts. The client was also provided a comprehensive competitive study of 36 companies including market shares and SWOT analysis for each industry segment.", "blurb_url": "", "case_study_url": "", "id": "25"},
		{"image": "matrix_2_7.jpg", "col" : "2", "row" : "7", "industry": "Adoption of New Mobile Shopping Technologies", "function_name": "", "case_study": "", "blurb": "Measured best practices and latest concepts on how to drive the adoption and use of cards for online business payment services, to consumer ecommerce transactions; specifically pertaining to existing successful promotional programs and execution tactics of online payment companies and top online merchants. Provided historical summaries on promotions, transactions, strategic partnerships, mergers and acquisitions, and online strategy for Credit Cards and Payments. Included landscape/competitive assessment and identification of leaders in promotional tactics and emerging technologies of online payments.", "blurb_url": "", "case_study_url": "", "id": "25"},
		{"image": "matrix_2_8.jpg", "col" : "2", "row" : "8", "industry": "Analysis of Logistic Service Providers for Metals", "function_name": "", "case_study": "", "blurb": "Provided a Market Assessment for third party logistic (3PL) services for mining commodities as a whole and with special regard to non-ferrous metals including analysis of  absolute and relative market size and major market determinants.", "blurb_url": "", "case_study_url": "", "id": "25"},
		{"image": "matrix_2_9.jpg", "col" : "2", "row" : "9", "industry": "Electrical Equipment for the Oil & Gas Industry", "function_name": "", "case_study": "", "blurb": "Provided a detailed analysis of the market size, market opportunities, customer needs, and competitive landscape for a range of Electrical Equipment in the Oil and Gas and Petrochemicals industries. Projected trends and profitability across various geographies and product lines over the next five years.", "blurb_url": "", "case_study_url": "", "id": "25"},
		{"image": "matrix_2_10.jpg", "col" : "2", "row" : "10", "industry": "Microcontroller Market Analysis", "function_name": "", "case_study": "", "blurb": "Provided an understanding of product roadmaps and related capabilities of selected semiconductor companies within the microcontroller space. Analyzed competitive landscape, technology trends, product roadmap, and reach into markets such as China.", "blurb_url": "", "case_study_url": "", "id": "25"},

		{"image": "matrix_3_1.jpg", "col" : "3", "row" : "1", "industry": "Attractiveness of Chemical Market Segments in Brazil", "function_name": "", "case_study": "", "blurb": "A medium sized intermediate chemical company in the US is challenged by their Board of Directors to explore growth opportunities outside of their home markets...", "blurb_url": "" + Drupal.settings.basePath + "sites/default/files/case_studies/Industrial Products Chemicals - Attractiveness of Chemical Market Segments in Brazil.pdf", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_2.jpg", "col" : "3", "row" : "2", "industry": "Security Services", "function_name": "", "case_study": "", "blurb": "Analyzed customer perception of various security service providers. Customer questions included the selection process and criteria to selecting a security provider as well as their outlook for future demand and relationships with providers.", "blurb_url": "", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_3.jpg", "col" : "3", "row" : "3", "industry": "Advanced Energy and Water Management", "function_name": "", "case_study": "", "blurb": "Explored the market opportunities and emerging technologies in the water and utilities sectors. Specifically, 10EQS provided an understanding of the market landscape of onsite renewables usage in the water and utilities sectors. Demand management techniques and associated costs were also assessed. Ultimately, this project helped the client strategize its expansion into the market and develop new product offerings.", "blurb_url": "", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_4.jpg", "col" : "3", "row" : "4", "industry": "Assessment of Franchise Financing in the US", "function_name": "", "case_study": "", "blurb": "Delivered an understanding of how US banks finance franchise businesses. Answered how banks in mature markets provide franchisee financing, dominant models, how they work with franchisors, the screening process, and loan portfolio management.", "blurb_url": "", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_5.jpg", "col" : "3", "row" : "5", "industry": "Environmental Radiation Monitor Analysis", "function_name": "", "case_study": "", "blurb": "Provided an assessment of the overall market size/opportunities/needs and competitive landscape for a new device in its radiation monitoring product line. Of the specific factors evaluated in the project included: key customer segments and their sizes, customer considerations in equipment purchase, key competitors their product offerings and a SWOT analysis of each.", "blurb_url": "", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_6.jpg", "col" : "3", "row" : "6", "industry": "International Markets for Dental Clinics", "function_name": "", "case_study": "", "blurb": "Analyzed 20 potential overseas markets for expansion potential. Studied 9 countries to provide a necessary basis for final decision-making.", "blurb_url": "", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_7.jpg", "col" : "3", "row" : "7", "industry": "Mobile Technology Market Analysis", "function_name": "", "case_study": "", "blurb": "Provided fact-based insights into market trends for women and technology at home and in the workplace over the next five years. Studied core demographics and trends from both consumer and professional perspectives with a primary focus on healthcare, retail and financial services related applications.", "blurb_url": "", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_8.jpg", "col" : "3", "row" : "8", "industry": "Global Mining Customer & Market Analysis", "function_name": "", "case_study": "", "blurb": "Provided an analysis of the global Mining Industry with a particular emphasis on Latin America, Canada and Australia. Among the areas we focused on included: up to date summaries on all mining related projects, projected capital expenditures by market players, and detailed listings of mines by metal and region.", "blurb_url": "", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_9.jpg", "col" : "3", "row" : "9", "industry": "Oil and Gas Capital Investment in Saudi Arabia", "function_name": "", "case_study": "", "blurb": "Provided a granular view of the Oil and Gas industry value chain elements and capital expenditures in specific Middle East regions for the near future including upstream, midstream and downstream investments. Analysis included a value chain validation, CAPEX and market size estimation, competitive landscape development, reservoir mapping and characterization, and product overview.", "blurb_url": "", "case_study_url": "", "id": "39"},
		{"image": "matrix_3_10.jpg", "col" : "3", "row" : "10", "industry": "Mobile Commerce in Latin America", "function_name": "", "case_study": "", "blurb": "Delivered a comprehensive understanding of the mobile commerce landscape in Argentina, Chile, Columbia, Mexico, and Puerto Rico by assessing market landscape, technological trends, applications, and approaches in each country.", "blurb_url": "", "case_study_url": "", "id": "39"},
		
		{"image": "matrix_4_1.jpg", "col" : "4", "row" : "1", "industry": "Analysis of Competing Substitutes in Key Ingredients for Laundry Detergents", "function_name": "", "case_study": "", "blurb": "10EQS analyzed the market share of DAS based vs. DBSP based OBAs for liquid/powder laundry detergents. Provided a comprehensive understanding of market structure, key players, and manufacturing/sourcing processes.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_2.jpg", "col" : "4", "row" : "2", "industry": "Consumer Headset Market Analysis", "function_name": "", "case_study": "", "blurb": "Analyzed the current status of the consumer headset market. Studied market size and structure, barriers for market entry, competitive landscape, major players and industry/technology trends.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_3.jpg", "col" : "4", "row" : "3", "industry": "Renewable Energies in Emerging Markets", "function_name": "", "case_study": "<p><strong>Market Sizing and Growth Prospects Related to Smart Grid</strong></p><p>10EQS delivered a market analysis study on the growing market for consumer electricity smart meters. We assessed hardware, software, system integration to the US grid and market for smart grid services to utilities, transmission/distribution and power generation companies.</p>", "blurb": "10EQS analyzed different models of private participation and public-private partnerships (PPP) in wind power development and micro-hydro power units within emerging markets.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_4.jpg", "col" : "4", "row" : "4", "industry": "Sovereign Wealth Fund Analysis", "function_name": "", "case_study": "", "blurb": "Provided a comprehensive overview and best practice analysis on the creation and operation of Sovereign Wealth Funds in selected geographies. Our assessment included a combination of existing data sets as well as insights from leading experts whom provided context on specific industry nuance.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_5.jpg", "col" : "4", "row" : "5", "industry": "Diesel Engine Catalyst Technology", "function_name": "", "case_study": "", "blurb": "Conducted market scan and evaluation of the profitability, investment potential and fit of diesel engine catalyst technology for the heavy-duty truck and bus sectors in China.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_6.jpg", "col" : "4", "row" : "6", "industry": "Lean Sigma Advisory Services", "function_name": "", "case_study": "", "blurb": "Provided an in-depth understanding of the current marketplace and customer beliefs on the value and business models related to offering Lean Sigma advisory services to U.S. hospitals. More specifically, the client wanted to understand the marketplace and customer beliefs around such offerings for &quot;delivery of care&quot; operational efficiencies and improvements.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_7.jpg", "col" : "4", "row" : "7", "industry": "Wireless Carrier Markets in Latin American Countries", "function_name": "", "case_study": "", "blurb": "Assessed wireless markets in selected Latin American Countries, including analysis of major wireless carriers, as well as 3rd party/independent tower companies in the respective markets. Additional focus on tower sharing or co-location agreements between carriers, planned wireless spectrum auctions, status of 3G and 4G network builds and a regulatory overview of the respective markets.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_8.jpg", "col" : "4", "row" : "8", "industry": "Mining Services & Software Market", "function_name": "", "case_study": "", "blurb": "Provided the client an understanding on the market sizes and profit pools, as well as the competitive landscape for a set of geographies, metals/minerals, and value chain elements.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_9.jpg", "col" : "4", "row" : "9", "industry": "Unconventional Gas Markets", "function_name": "", "case_study": "", "blurb": "Analyzed the capital expenditure market for compressed and liquefied natural gas markets as transportation fuels. Assessed market size, value chain, adoption rates, pricing structure, competitors, and customers, focusing on Asia, Australia, Europe, and Latin America.", "blurb_url": "", "case_study_url": "", "id": "45"},
		{"image": "matrix_4_10.jpg", "col" : "4", "row" : "10", "industry": "Advertising on Social Networks", "function_name": "", "case_study": "", "blurb": "Assessed trends in advertising spend and breakdown between traditional and on-line media, by industry/product category, and its expected evolution over the next few years. Additionally, 10EQS provided a competitive analysis of current and projected industry leaders and their best practices. Our analysis included data on: current and projected advertising spend in traditional media vs. Internet by and across industry, breakdown of industries, product categories and brands that are most successful/prevalent in use of Facebook fan pages and groups, along with analysis on trends in Online/Social Media Advertising/Marketing, and current/projected growth and use of social media by industry leaders.", "blurb_url": "", "case_study_url": "", "id": "45"},

		{"image": "matrix_5_1.jpg", "col" : "5", "row" : "1", "industry": "Identifying Acquisition Opportunities in the Chemicals Market", "function_name": "", "case_study": "", "blurb": "Analyzed potential growth and acquisition opportunities for the client within new technology space in the chemicals industry. Helped guide client's strategies in identifying growth opportunities, where the client should invest, and how the client can serve new markets.", "blurb_url": "", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_2.jpg", "col" : "5", "row" : "2", "industry": "Mergers & Acquisitions in the Poultry Industry", "function_name": "", "case_study": "", "blurb": "Analyzed and prioritized potential acquirers for the client's turkey breeding company. Analyzed the cross-border M&A market for turkey breeding business, including major transactions, valuation levels, and value drivers.", "blurb_url": "", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_3.jpg", "col" : "5", "row" : "3", "industry": "Target and Opportunity Assessment for the Biomass Market in Europe", "function_name": "", "case_study": "", "blurb": "Identified and evaluated opportunities to market Russian reserves of forest biomass in the European market, and possibly globally. Provided an understanding of the current and future biomass feedstock market for alternative energy production, the competitive landscape and to identify areas of opportunities to invest in biofuels.", "blurb_url": "", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_4.jpg", "col" : "5", "row" : "4", "industry": "Potential Acquisition Profiling of Specialized Trading Companies", "function_name": "", "case_study": "", "blurb": "Analyzed 34 potential target firms including organizational set up, expansion/acquisition/capital raising plans, key success factors and best practices in risk management and recruitment. The client received detailed profiles of all firms along with recommendations for acquisitions/partnerships based on performance indicators, investment capital needs and other expert insights.", "blurb_url": "" + Drupal.settings.basePath + "sites/default/files/case_studies/Financial Services - M&A Investment Target Search and Analysis.pdf", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_5.jpg", "col" : "5", "row" : "5", "industry": "Due Diligence on Growth Prospects in Materials Testing in the Aero-Defense Industry", "function_name": "", "case_study": "", "blurb": "Conducted operational due diligence on growth prospects and cost saving/synergy potentials in the materials testing industry for the aero-defense industry.", "blurb_url": "", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_6.jpg", "col" : "5", "row" : "6", "industry": "Biotechnology Equipment Market Analysis", "function_name": "", "case_study": "", "blurb": "Conducted expert interviews in specific regions to identify possible user response to new lower priced equipment. Identified market needs including the frequency and type of usage, and user preferences in terms of product performance (speed, quality, etc.)", "blurb_url": "", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_7.jpg", "col" : "5", "row" : "7", "industry": "Printing & Publishing M&A", "function_name": "", "case_study": "", "blurb": "Analyzed which type of companies by region/industry would probably be most interested in acquiring a client's facility. Developed a methodology to identify, select and prioritize potential acquirers based on certain criteria.", "blurb_url": "", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_8.jpg", "col" : "5", "row" : "8", "industry": "Recycling and Waste Management Markets in Europe", "function_name": "", "case_study": "", "blurb": "Analyzed the recycling and waste management market in Europe. Studied battery and scrap metal recycling including volumes/rates, market sizing, sales, major market players, costs and tax structure by geographic region and metal type.", "blurb_url": "", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_9.jpg", "col" : "5", "row" : "9", "industry": "Economics of Offshore Drilling Rigs", "function_name": "", "case_study": "", "blurb": "Determined the main economic (budgeting) issues on drilling rig revenues, including maintenance and dry-dock on a global scale.", "blurb_url": "", "case_study_url": "", "id": "55"},
		{"image": "matrix_5_10.jpg", "col" : "5", "row" : "10", "industry": "Intellectual Property Portfolio Acquisition", "function_name": "", "case_study": "", "blurb": "Identified investment bankers and boutique firms who would most likely be successful in marketing and selling the client's Intellectual Property globally. Approached a number of specialty firms within the 10EQS network who may have direct interest in the client's IP.", "blurb_url": "", "case_study_url": "", "id": "55"},

		{"image": "matrix_6_1.jpg", "col" : "6", "row" : "1", "industry": "Price Elasticity of Petrochemical Products", "function_name": "", "case_study": "", "blurb": "An American petrochemical company is trying to gain a better understanding of the price elasticity of a key raw material...", "blurb_url": "" + Drupal.settings.basePath + "sites/default/files/case_studies/Petrochemicals - Price Elasticity of Petrochemical Products.pdf", "case_study_url": "", "id": "62"},
		{"image": "matrix_6_2.jpg", "col" : "6", "row" : "2", "industry": "Light Commercial Vehicles Cost Structure Analysis", "function_name": "", "case_study": "", "blurb": "Benchmarked cost and price structures of Light Commercial Vehicles in Europe including dealer cost, distributor cost, OEM margins and operating costs.", "blurb_url": "", "case_study_url": "", "id": "63"},
		{"image": "matrix_6_3.jpg", "col" : "6", "row" : "3", "industry": "Polysilicon Manufacturing Analysis", "function_name": "", "case_study": "", "blurb": "Analyzed the Polysilicon Manufacturing market and various companies and technologies that exist in that space. Provided insights from experts in Photovoltaic Silicon wafer processing and Polysilicon Manufacturing.", "blurb_url": "", "case_study_url": "", "id": "64"},
		{"image": "matrix_6_4.jpg", "col" : "6", "row" : "4", "industry": "Compensation and Incentive Schemes in the Eastern European Banking Market", "function_name": "", "case_study": "", "blurb": "10EQS provided benchmarking for the compensation rates of high level management in Financial Service Companies including base compensation, bonus payments, and incentive schemes - before, during, and after the financial crisis. Analysis was used to inform contract negotiations with top-level management.", "blurb_url": "", "case_study_url": "", "id": "65"},
		{"image": "matrix_6_5.jpg", "col" : "6", "row" : "5", "industry": "Cost and Margin Analysis of Industrial Automation Market", "function_name": "", "case_study": "", "blurb": "Analyzed cost and profitability structure of a global industrial parts manufacturer. Included operating profit, existing customer figures, total employee figures, quantity of sales offices, total revenue and sales & marketing costs.", "blurb_url": "", "case_study_url": "", "id": "66"},
		{"image": "matrix_6_6.jpg", "col" : "6", "row" : "6", "industry": "Value Drivers for Biologic Therapeutic Companies", "function_name": "", "case_study": "", "blurb": "Assessed the value drivers for biologics companies, including industry trends and expenditures for R&D and SG&A, financing structures and industry perspectives. Analysis also covered several leading product P&L examples.", "blurb_url": "", "case_study_url": "", "id": "67"},
		{"image": "matrix_6_7.jpg", "col" : "6", "row" : "7", "industry": "Economic Impact of Navigation Systems", "function_name": "", "case_study": "", "blurb": "To determine the effect of introducing navigation technologies in emerging markets, 10EQS evaluated effects on the overall economy and selected industry on implementation in other countries, such as the US, Europe and Japan.", "blurb_url": "", "case_study_url": "", "id": "68"},
		{"image": "matrix_6_8.jpg", "col" : "6", "row" : "8", "industry": "Coal-Fired Power Stations in China", "function_name": "", "case_study": "", "blurb": "Analyzed providers of small coal-fired power stations in China. Down-selected and recommended the most suitable providers based on factors such as product offering, cost, required capex estimates and overall economics.", "blurb_url": "", "case_study_url": "", "id": "610"},
		{"image": "matrix_6_9.jpg", "col" : "6", "row" : "9", "industry": "Price Elasticity of Petrochemical Products", "function_name": "", "case_study": "", "blurb": "An American petrochemical company is trying to gain a better understanding of the price elasticity of a key raw material...", "blurb_url": "", "case_study_url": "", "id": "610"},
		{"image": "matrix_6_10.jpg", "col" : "6", "row" : "10", "industry": "Software Company Sales Compensation Structure Analysis", "function_name": "", "case_study": "", "blurb": "Analyzed the organizational/compensational structures within large technology enterprises. Included the change in gross profit margin (potential change in compensation structure) and insights from various industry experts.", "blurb_url": "", "case_study_url": "", "id": "610"},
		
		{"image": "matrix_7_1.jpg", "col" : "7", "row" : "1", "industry": "Carbon Energy Storage Market Analysis", "function_name": "", "case_study": "", "blurb": "Provided an understanding of the current and emerging market for highly purified carbon used in advanced lead-acid battery and ultracapacitor technologies, both in terms of market size and market share relative to various demand, application and value proposition scenarios.", "blurb_url": "", "case_study_url": "", "id": "73"},
		{"image": "matrix_7_2.jpg", "col" : "7", "row" : "2", "industry": "Confection Market Assessment", "function_name": "", "case_study": "", "blurb": "Provided a detailed view of the confection market brands and markets across five different countries including the US/Canada, China, India, Mexico and Brazil. The study includes an analysis of different companies&#39; go-to-market approaches, specific product portfolios, manufacturing capabilities, distribution networks and financial performance.", "blurb_url": "", "case_study_url": "", "id": "75"},
		{"image": "matrix_7_3.jpg", "col" : "7", "row" : "3", "industry": "Eco Energy Sector Analysis", "function_name": "", "case_study": "", "blurb": "Provided market sizing estimates in 2020 and 2030 for key sectors in the eco market. Performed deep dive into the most promising 90 sectors across 10 regions in the efficient energy sector and identified opportunities for expansion into new growth markets.", "blurb_url": "", "case_study_url": "", "id": "77"},
		{"image": "matrix_7_4.jpg", "col" : "7", "row" : "4", "industry": "Opportunity to Enter the Credit Risk Ratings Market", "function_name": "", "case_study": "", "blurb": "Provided an assessment on the market size of the credit rating industry. Our analysis included insights on major and minor players, the number of loans/obligation they rate, industries dynamics of players attempting to enter the market and potential efforts at consolidation.", "blurb_url": "", "case_study_url": "", "id": "77"},
		{"image": "matrix_7_5.jpg", "col" : "7", "row" : "5", "industry": "Assessment of the Plywood Market in China and India", "function_name": "", "case_study": "", "blurb": "Provided an analysis to understand the domestic consumption and price of different types of Plywood in China and India. Additionally, we provided insights around the main usage of plywood and the total country plywood production by segment (furniture, construction, transportation, shipbuilding, toys and audio cabinets).", "blurb_url": "", "case_study_url": "", "id": "77"},
		{"image": "matrix_7_6.jpg", "col" : "7", "row" : "6", "industry": "Advisory Services for the Reduction of Hospital Re-Admissions Related to Heart Failure", "function_name": "", "case_study": "", "blurb": "Produced an industry scan of the market landscape for certain hospital advisory services. Analyzed what kinds of advisory services are typically bought by hospitals for the reduction of heart failure readmissions and key metrics used to determine the success of these services.", "blurb_url": "", "case_study_url": "", "id": "77"},
		{"image": "matrix_7_7.jpg", "col" : "7", "row" : "7", "industry": "Pay TV Market Opportunity Assessment", "function_name": "", "case_study": "", "blurb": "A large diversified company in Europe is interested in exploring opportunities to enter the Pay TV market...", "blurb_url": "" + Drupal.settings.basePath + "sites/default/files/case_studies/Media Industry - Pay TV Market Opportunity Assessment.pdf", "case_study_url": "", "id": "77"},
		{"image": "matrix_7_8.jpg", "col" : "7", "row" : "8", "industry": "Attractive Growth Segments in Recycled Materials", "function_name": "", "case_study": "", "blurb": "Provided analysis on the Recycling and Waste Management Market in Europe. Our assessment included insights on battery and scrap metal recycling including volumes/rates, market sizing, sales, major market players, costs and tax structure by geographic region and metal type.", "blurb_url": "", "case_study_url": "", "id": "77"},
		{"image": "matrix_7_9.jpg", "col" : "7", "row" : "9", "industry": "US Shale Plays", "function_name": "", "case_study": "", "blurb": "Developed a complete understanding of the market landscape and management operations for the leading shale plays. Benchmarked E&P companies' land management, revenue accounting, and division of interest practices. Analysis included performance projections, market shares, operational effectiveness, owner relations management, and best practice in supply chain for unconventionals.", "blurb_url": "", "case_study_url": "", "id": "77"},
		{"image": "matrix_7_10.jpg", "col" : "7", "row" : "10", "industry": "Mobile Fashion Apps in China", "function_name": "", "case_study": "", "blurb": "Prepared a comprehensive qualitative view of the landscape of fashion oriented mobile phone applications in China and an understanding of current and emerging applications, the evolving application landscape, and a deep dive on the leading applications in each of the discovered fashion application categories.", "blurb_url": "", "case_study_url": "", "id": "77"},

		{"image": "matrix_8_1.jpg", "col" : "8", "row" : "1", "industry": "Plastics Machinery & Equipment", "function_name": "", "case_study": "", "blurb": "Assessed the global and regional market dynamics for plastics processing machinery and equipment. Analysis helped the client assess its competitors' current and planned offerings, market sizes, growth rates, and suggested various growth opportunities. Final deliverable included a comprehensive quantitative model to support findings and analysis in support of the client's growth strategy.", "blurb_url": "", "case_study_url": "", "id": "83"},
		{"image": "matrix_8_2.jpg", "col" : "8", "row" : "2", "industry": "Top Fashion Brands in Russia", "function_name": "", "case_study": "<p><strong>Labeling Equipment Technology & Trend Analysis</strong></p><p>Provided an in-depth analysis of the current and emerging technologies and trends in consumer product labeling. Developed a detailed quantitative and qualitative analysis of the supplier landscape, current and projected labeling equipment sales, performance and pricing characteristics, and sales and service models.</p>", "blurb": "Analyzed performance and market position of leading fashion brands in Russia, including revenue, market share, growth trends and key adoption drivers. Included international and national brands across four segments: luxury, affordable luxury (aspirational), mainstream and discount.", "blurb_url": "", "case_study_url": "", "id": "84"},
		{"image": "matrix_8_3.jpg", "col" : "8", "row" : "3", "industry": "Start-ups in the Energy Sector", "function_name": "", "case_study": "", "blurb": "Identified and assessed the anticipated level of innovation and disruption in various energy related sectors including: solar, biofuels, wind, aviation and public transportation. Selected the sectors with the highest level of anticipated disruption within the next 5-15 years.", "blurb_url": "", "case_study_url": "", "id": "87"},
		{"image": "matrix_8_4.jpg", "col" : "8", "row" : "4", "industry": "Innovative Car Insurance Products", "function_name": "", "case_study": "", "blurb": "Analyzed the market for Innovative Auto Insurance products to help the client position itself to take advantage of these markets. We conducted a study on the current state of the market including: the different types of insurance existing and planned, major players and their offerings and value propositions, market best practices, and the current value chain for a specific innovative growth market.", "blurb_url": "", "case_study_url": "", "id": "87"},
		{"image": "matrix_8_5.jpg", "col" : "8", "row" : "5", "industry": "Propulsion Manufacturing Industry Trends", "function_name": "", "case_study": "", "blurb": "Analyzed the propulsion engine industry structure across different geographies including Europe, the US, China, India and Japan. Analysis included business models of propulsion engine manufacturers (product portfolios, synergies, level of vertical integration, profit models) and public sector policy in the propulsion engine industry (ownership structures, competition policies, market openness).", "blurb_url": "", "case_study_url": "", "id": "87"},
		{"image": "matrix_8_6.jpg", "col" : "8", "row" : "6", "industry": "Generic Injectables", "function_name": "", "case_study": "", "blurb": "Identified and prioritized the top 150 products that would represent the greatest revenue opportunities across injectables and opthalmic products using current and future potential revenue.", "blurb_url": "", "case_study_url": "", "id": "87"},
		{"image": "matrix_8_7.jpg", "col" : "8", "row" : "7", "industry": "TV Media Audience Analysis", "function_name": "", "case_study": "", "blurb": "Analyzed market size of Ethnic/Demographic segments and potential for &quot;niche&quot; subscriber groups to provide insights into asset investment in the broadcasting/tv network and cable industry.", "blurb_url": "", "case_study_url": "", "id": "87"},
		{"image": "matrix_8_8.jpg", "col" : "8", "row" : "8", "industry": "Electrical Equipment for the Mining Industry", "function_name": "", "case_study": "", "blurb": "Provided a detailed analysis of the market size, market opportunities, customer needs, and competitive landscape for a range of Electrical Equipment in the Mining industry. Projected trends and profitability across various geographies and product lines over the next five years.", "blurb_url": "", "case_study_url": "", "id": "87"},
		{"image": "matrix_8_9.jpg", "col" : "8", "row" : "9", "industry": "Oil & Gas Industry Radar Scan", "function_name": "", "case_study": "", "blurb": "Conducted an expert-driven scan of the Oil & Gas sector to generate insights on key emerging strategic issues.", "blurb_url": "", "case_study_url": "", "id": "87"},
		{"image": "matrix_8_10.jpg", "col" : "8", "row" : "10", "industry": "Mobile Payments: Trends and Technologies", "function_name": "", "case_study": "<p><strong>Online Games and Hosting Infrastructure Market and Trends</strong></p><p>Assessed emerging trends in on-line games in Asia and North America, including user preferences, growth projections, and technology and service implications for on-line game infrastructure (hosting) providers across various gaming segments. Included competitive assessment of both on-line game content developers/publishers and hosting providers as well as emerging technology and service stack requirements including micro-payment and advertising placement services.</p>", "blurb": "A medium sized European retail bank with a focus on consumer lending assesses expanding its mobile phone banking offer into mobile contactless payments...", "blurb_url": "" + Drupal.settings.basePath + "sites/default/files/case_studies/Mobile Payments - Mobile Payments Trends and Technologies.pdf", "case_study_url": "", "id": "87"}
	]
};

function show_matrix(){
	var matrix_html = '<table cellpadding="0" cellspacing="0">';
	var row = 1;
	var col = 1;
	
	/* display rows */
	for (var heading in matrixJSON.headings.left){
		matrix_html += '<tr>';			
        matrix_html += '<td class="heading-left">' + matrixJSON.headings.left[heading].display_name + '</td>';
        matrix_html += '<td class="spacer field"></td>';                                
        matrix_html += '<td class="field field' + row + '1"><div class="field"></div></td>';
        matrix_html += '<td class="field field' + row + '2"><div class="field"></div></td>';
        matrix_html += '<td class="field field' + row + '3"><div class="field"></div></td>';
        matrix_html += '<td class="field field' + row + '4"><div class="field"></div></td>';
        matrix_html += '<td class="field field' + row + '5"><div class="field"></div></td>';
        matrix_html += '<td class="field field' + row + '6"><div class="field"></div></td>';
        matrix_html += '<td class="field field' + row + '7"><div class="field"></div></td>';
        matrix_html += '<td class="last field field' + row + '8"><div class="field"></div></td>';
		matrix_html += '</tr>';
		row++;		
	}
	
	/* display bottom row */	
	matrix_html += '<tr>';
	matrix_html += '<td class="heading-left"></td>';
	matrix_html += '<td class="spacer blank field"></td>';
	for (var heading in matrixJSON.headings.bottom){
		matrix_html += '<td class="heading-bottom">' + matrixJSON.headings.bottom[heading].display_name + '</td>';
	}
	matrix_html += '</tr>'; 	
	matrix_html += '</table>';
	
	/* add matrix to DOM */		
	$('.matrix').append(matrix_html);
	
	/* display popups */
	var popup_html = '';
	for (popup in matrixJSON.popups){
		popup_html = '';
        eval("mouseOverTracker" + matrixJSON.popups[popup].id + " = new MouseoverTracker(pageTracker, matrixJSON.popups[popup].industry);");
        eval("timeTracker" + matrixJSON.popups[popup].id + " = new TimeTracker();");
		popup_html += '<a href="javascript:void(0);" id="' + matrixJSON.popups[popup].id + '" onMouseOver="eval(\'mouseOverTracker\' + this.id +\'._trackMouseover(this.id);\');" onMouseOut="eval(\'mouseOverTracker\' + this.id +\'._trackMouseout(this.id);\');"><img src="' + Drupal.settings.basePath + 'sites/all/themes/teneqs_v1/' + matrix_image_path + matrixJSON.popups[popup].image + '" alt="" /></a>';
		popup_html += '<div class="popup"><div class="inner">';
		popup_html += '<p><strong>' + matrixJSON.popups[popup].industry + '</strong>' + matrixJSON.popups[popup].function_name + '</p>';
		popup_html += '<p>' + matrixJSON.popups[popup].blurb + '</p>';
		if (matrixJSON.popups[popup].blurb_url) {
		  popup_html += '<p><a href="' + matrixJSON.popups[popup].blurb_url + '" class="arrow-red" target="_blank">Read more</a></p>';
		}
		if (matrixJSON.popups[popup].case_study) {
		  popup_html += '<div>&nbsp;</div>';
		  popup_html += matrixJSON.popups[popup].case_study;
		}
		if (matrixJSON.popups[popup].case_study_url) {
		  popup_html += '<p><a href="' + matrixJSON.popups[popup].case_study_url + '" class="arrow-red" target="_blank">Read more</a></p>';
		}
		popup_html += '</div><div class="bottom"></div></div>';
		$('.matrix .field' + matrixJSON.popups[popup].row + matrixJSON.popups[popup].col + ' div').append(popup_html);
	}	
	
	/* offset popups */	
	$('.matrix .popup').each(function(){
		var top =  0 - $(this).height();
		$(this).css( { top : top + 'px', left : '-138px' } );
	});
	
	/* bind to popup links */
	$('.matrix .field').bind('mouseenter', function(){
		//$('.matrix .popup').css( { display : 'none'} );
		$(this).find('.popup').fadeIn('fast');
		//console.log(debug + 'in');
		//debug++;
	});
	
	$('.matrix .field').bind('mouseleave', function(){
		$(this).find('.popup').stop().css( { display : 'none', opacity : 1} );
		//console.log(debug + 'out');		
		//debug++;		
	});	
}